### ISSUE TITLE
Please add jackett to mediastack

### ISSUE THREAD

**Issue by 007-deli** [geekau/mediastack#31]
Please add Jackett to mediastack - https://github.com/Jackett/Jackett

**Comment by geekau** [comment]
Can you test this Jacket configuration, I've used the LinuxServer image as they have the ThemeParks mod, which I have in the other containers for consistancy.

I haven't used Jackett or tested this configuration, so not sure if the volume mapping for `- ${FOLDER_FOR_MEDIA:?err}:/data` is 100% correct, but it will get you started. The /data volume mapped inside the containers have several download directories, I'm just not sure how Jackett uses it... please test and advise.

If you're using the newly released MediaStack configurations, I've used the Docker labels to tag the container for Traefik / Authentik / SSO etc.. so it can be access remotely with the Traefik reverse proxy, if the users authenticate successfully.

**### To Install:**

Add the following to your **`.env`** file:

```
WEBUI_PORT_JACKETT=9117       # WebUI Portal: Jackett
```

> NOTE: If you need to change ports due to conflicts / preference, change the port number above, in the **`.env`** file.


Add the following to your **`docker-compose.yaml`** file, in the Gluetun "**ports;**" section:

```
      - ${WEBUI_PORT_JACKETT:?err}:9117             # Configured in Gluetun VPN container
```

Add the Jackett configuration to your **`docker-compose.yaml`** file:

```
###########################################################################
###########################################################################
##
##  Docker Compose File: Jackett (LinuxServer.io)
##  Function: Movie Library Manager
##
##  Documentation: https://docs.linuxserver.io/images/docker-jackett
##
###########################################################################
###########################################################################
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${FOLDER_FOR_MEDIA:?err}:/data
      - ${FOLDER_FOR_DATA:?err}/jackett:/config
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:jackett
      - TP_THEME=${TP_THEME:?err}
    network_mode: "service:gluetun"
#    ports:
#      - ${WEBUI_PORT_JACKETT:?err}:9117             # Configured in Gluetun VPN container
    labels:
      - traefik.enable=true
    # ROUTERS
      - traefik.http.routers.jackett.service=jackett
      - traefik.http.routers.jackett.rule=Host(`jackett.${CLOUDFLARE_DNS_ZONE:?err}`)
      - traefik.http.routers.jackett.entrypoints=secureweb
      - traefik.http.routers.jackett.middlewares=authentik-forwardauth@file,security-headers@file,traefik-bouncer@file
    # SERVICES
      - traefik.http.services.jackett.loadbalancer.server.scheme=http
      - traefik.http.services.jackett.loadbalancer.server.port=9117
    # MIDDLEWARES
```
