### ISSUE TITLE
Near idea, but a question...

### ISSUE THREAD

**Issue by IITYWYBMAB** [geekau/mediastack#32]
I like that you're tying everything together, however for a lot of users this might be restrictive. I think the goal of the project is to make things easier for a complete stack, however I'm curious to know it's easily modifiable to add and remove components i have a highly customized stack already and would like to pick and choose. I appreciate any input you can give and also your efforts!

**Comment by geekau** [comment]
I was completely lost about 2 years ago on how to set up Docker and all the *ARR stacks and thought there must be an easier way for new users, and we started the project with one of the main objectives to simply make it easy for user users. IMO MediaStack is one of the easiet to use / set up for new starters, and we've also concentrated on security / privacy for any outbound / download connections, by routing them Gluetun VPN.

While the new configuration is contained in a single docker compose file, it should be treated as a reference design, so you can remove as many of the configurations out, as long as you keep the Gluetun VPN container, to provide privacy for the outbound security.

Additionally, you can very easily add new docker applications into the docker compose file, to further customise your home MediaStack.

For example, the other issue someone logged was to add Jackett into MediaStack - I posted the working configuration into the thread:

https://github.com/geekau/mediastack/issues/31

As long as the basic principles are used in the linked thread, you'll be able to add as many docker applications as you need.

Hope this helps.

**Comment by yarafie** [comment]
Maybe look at using includes in docker compose
each include is it's own compose file.

This is docker-compose.yml
each compose is in its own directory just for organization purposes you can flatten it completly into one directory if you want

#version: "3.9"
#Includes
include:
  - gluetun/gluetun.yml
  - compose1/compose1.yml
  - compose2/compose2.yml
  - ....
  - .....
#Base services
#Network Definition
networks:
  mediastack:
    name: mediastack
    driver: bridge
#    enable_ipv6: true
    ipam:
      config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1

**Comment by yarafie** [comment]
Maybe look at using includes in docker compose
each include is it's own compose file.

This is docker-compose.yml
each compose is in its own directory just for organization purposes you can flatten it completly into one directory if you want

```
#version: "3.9"
#Includes
include:
  - gluetun/gluetun.yml
  - compose1/compose1.yml
  - compose2/compose2.yml
  - ....
  - .....
#Base services
#Network Definition
networks:
  mediastack:
    name: mediastack
    driver: bridge
#    enable_ipv6: true
    ipam:
      config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1
```
