### ISSUE TITLE
Traefik Reverse Proxy Configured Incorrectly for Qbittorrent

### ISSUE THREAD

**Issue by gingeredcake** [geekau/mediastack#36]
Traefik doesn't see qbittorrent on the mini-download-vpn version, because qbittorrent is on the gluetun network, not the media-stack network. This results in 404 errors at qbittorrent.example.com, and in the traefik dashboard the qbittorrent service is not there at all.

Traefik can reverse proxy to the qbittorrent webui if the labels on the qbittorrent service are moved to the gluetun service.

Working abridged gluetun config
```
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp                         # Gluetun Local Network HTTP proxy
      - 8388:8388/tcp                         # Gluetun Local Network Shadowsocks
      - 8388:8388/udp                         # Gluetun Local Network Shadowsocks
      - ${GLUETUN_CONTROL_PORT:?err}:${GLUETUN_CONTROL_PORT:?err} # Gluetun Status Port
    environment:
........
    labels:
      - traefik.enable=true
    # ROUTERS
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${CLOUDFLARE_DNS_ZONE:?err}`)
      - traefik.http.routers.qbittorrent.entrypoints=secureweb
      - traefik.http.routers.qbittorrent.middlewares=authentik-forwardauth@file,security-headers@file,traefik-bouncer@file
    # SERVICES
      - traefik.http.services.qbittorrent.loadbalancer.server.scheme=http
      - traefik.http.services.qbittorrent.loadbalancer.server.port=${WEBUI_PORT_QBITTORRENT:?err}
```
