### ISSUE TITLE
Unable to save config changes in Qbittorent

### ISSUE THREAD

**Issue by krt1k** [geekau/mediastack#44]
I was unable to save configuration changes such as new admin password, download dir, or anything. The save button in the popup window make no sense.

and I also face torrent download error. I am unable to find any logs in the container as well.

I am using unmodified version of full-download-vpn compose file. 

![Image](https://github.com/user-attachments/assets/e78575c9-5eb5-49df-8ce2-5f10d8ed7a2d)

`❯ docker compose logs qbittorrent -f

qbittorrent  | [mod-init] Running Docker Modification Logic
qbittorrent  | [mod-init] Adding themepark-dev/theme.park:qbittorrent to container
qbittorrent  | [mod-init] Downloading themepark-dev/theme.park:qbittorrent from ghcr.io
qbittorrent  | [mod-init] Installing themepark-dev/theme.park:qbittorrent
qbittorrent  | [mod-init] themepark-dev/theme.park:qbittorrent applied to container
qbittorrent  | [migrations] started
qbittorrent  | [migrations] no migrations found
qbittorrent  | ───────────────────────────────────────
qbittorrent  | 
qbittorrent  |       ██╗     ███████╗██╗ ██████╗
qbittorrent  |       ██║     ██╔════╝██║██╔═══██╗
qbittorrent  |       ██║     ███████╗██║██║   ██║
qbittorrent  |       ██║     ╚════██║██║██║   ██║
qbittorrent  |       ███████╗███████║██║╚██████╔╝
qbittorrent  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
qbittorrent  | 
qbittorrent  |    Brought to you by linuxserver.io
qbittorrent  | ───────────────────────────────────────
qbittorrent  | 
qbittorrent  | To support LSIO projects visit:
qbittorrent  | https://www.linuxserver.io/donate/
qbittorrent  | 
qbittorrent  | ───────────────────────────────────────
qbittorrent  | GID/UID
qbittorrent  | ───────────────────────────────────────
qbittorrent  | 
qbittorrent  | User UID:    1000
qbittorrent  | User GID:    1000
qbittorrent  | ───────────────────────────────────────
qbittorrent  | Linuxserver.io version: 5.1.1-r0-ls400
qbittorrent  | Build-date: 2025-06-25T02:33:19+00:00
qbittorrent  | ───────────────────────────────────────
qbittorrent  |     
qbittorrent  | [pkg-install-init] **** Installing all mod packages ****
qbittorrent  | fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
qbittorrent  | fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
qbittorrent  | (1/6) Installing git (2.50.0-r0)
qbittorrent  | (2/6) Installing git-init-template (2.50.0-r0)
qbittorrent  | (3/6) Installing perl (5.40.2-r0)
qbittorrent  | (4/6) Installing perl-error (0.17030-r0)
qbittorrent  | (5/6) Installing perl-git (2.50.0-r0)
qbittorrent  | (6/6) Installing git-perl (2.50.0-r0)
qbittorrent  | Executing busybox-1.37.0-r18.trigger
qbittorrent  | OK: 149 MiB in 90 packages
qbittorrent  | ------------------------------
qbittorrent  | | qBittorrent theme.park Mod |
qbittorrent  | ------------------------------
qbittorrent  | QBITTORRENT_VERSION not set. Using the latest stable.
qbittorrent  | Variables set:
qbittorrent  | 'APP_FILEPATH'=/config/qBittorrent/qBittorrent.conf
qbittorrent  | 'TP_DISABLE_THEME'=
qbittorrent  | 'TP_HOTIO'=
qbittorrent  | 'TP_DOMAIN'=
qbittorrent  | 'TP_COMMUNITY_THEME'=
qbittorrent  | 'TP_SCHEME'=
qbittorrent  | 'QBITTORRENT_VERSION'=5.1.1
qbittorrent  | 'TP_THEME'=nord
qbittorrent  | 
qbittorrent  | No domain set, defaulting to theme-park.dev
qbittorrent  | No scheme set, defaulting to https
qbittorrent  | ---------------------------------------
qbittorrent  | | Downloading WebUI files from github |
qbittorrent  | ---------------------------------------
qbittorrent  | 
qbittorrent  | Downloading qBittorrent to /temp
qbittorrent  | Downloading WebUI for version: 5.1.1
qbittorrent  | Cloning into '/temp'...
qbittorrent  | warning: refs/tags/release-5.1.1 0843886dc972bb4170154614b1062bb6429fd62f is not a commit!
qbittorrent  | Note: switching to 'ea9f3800ce70ded6db66b2c9f0d2f0513399e969'.
qbittorrent  | 
qbittorrent  | You are in 'detached HEAD' state. You can look around, make experimental
qbittorrent  | changes and commit them, and you can discard any commits you make in this
qbittorrent  | state without impacting any branches by switching back to a branch.
qbittorrent  | 
qbittorrent  | If you want to create a new branch to retain commits you create, you may
qbittorrent  | do so (now or later) by using -c with the switch command. Example:
qbittorrent  | 
qbittorrent  |   git switch -c <new-branch-name>
qbittorrent  | 
qbittorrent  | Or undo this operation with:
qbittorrent  | 
qbittorrent  |   git switch -
qbittorrent  | 
qbittorrent  | Turn off this advice by setting config variable advice.detachedHead to false
qbittorrent  | 
qbittorrent  | 
qbittorrent  | Download finished
qbittorrent  | 
qbittorrent  | 
qbittorrent  | Copy finished
qbittorrent  | 
qbittorrent  | 
qbittorrent  | Cleanup finished
qbittorrent  | 
qbittorrent  | ---------------------------------------
qbittorrent  | | Adding the stylesheet to html files |
qbittorrent  | ---------------------------------------
qbittorrent  | Stylesheet set to nord on /themepark/public/index.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/editfeedurl.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/newfeed.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/rename_feed.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/rename_file.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/index.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/rename.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/confirmruledeletion.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/confirmruleclear.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/newtag.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/download.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/rename_files.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/edittracker.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/confirmtrackerdeletion.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/logTabs.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/confirmRecheck.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/installsearchplugin.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/confirmAutoTMM.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/about.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/aboutToolbar.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/rss.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/confirmdeletion.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/properties.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/propertiesToolbar.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/transferlist.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/cookies.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/filters.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/statistics.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/log.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/rssDownloader.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/preferencesToolbar.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/search.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/searchplugins.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/views/preferences.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/addpeers.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/shareratio.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/addwebseeds.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/uploadlimit.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/downloadlimit.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/editwebseed.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/rename_rule.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/upload.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/addtrackers.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/confirmfeeddeletion.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/newcategory.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/setlocation.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/newfolder.html
qbittorrent  | 
qbittorrent  | Stylesheet set to nord on /themepark/private/newrule.html
qbittorrent  | 
qbittorrent  | ------------------------------------------------------------
qbittorrent  | | Cleaning files in /themepark for any translation text... |
qbittorrent  | ------------------------------------------------------------
qbittorrent  | [custom-init] No custom files found, skipping...
qbittorrent  | WebUI will be started shortly after internal preparations. Please wait...
qbittorrent  | 
qbittorrent  | ******** Information ********
qbittorrent  | To control qBittorrent, access the WebUI at: http://localhost:8200
qbittorrent  | The WebUI administrator username is: admin
qbittorrent  | The WebUI administrator password was not set. A temporary password is provided for this session: A5KbdupwR
qbittorrent  | You should set your own password in program preferences.
qbittorrent  | Connection to localhost (::1) 8200 port [tcp/*] succeeded!
qbittorrent  | [ls.io-init] done.
`

**Comment by krt1k** [comment]
It was fixed now!

The problem is with the lscr.io/linuxserver/qbittorrent:latest image (which is v5.1.1 for now). So i manually specified the previous version (v5.0.1), and somehow the qbittorrent container updates the webui back the latest version (v5.1.1) which is causing the problem.

So, then I manually set the docker environment variable, `QBITTORRENT_VERSION=5.0.1`, Then everything works fine now!

Here's the final working docker-compose part for qBittorrent:
```
###########################################################################
###########################################################################
##
##  Docker Compose File: qBittorrent (LinuxServer.io)
##  Function: Torrent Download Client
##
##  Documentation: https://docs.linuxserver.io/images/docker-qbittorrent
##
###########################################################################
###########################################################################
  qbittorrent:
    image: linuxserver/qbittorrent:5.0.1
    container_name: qbittorrent
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    volumes:
      - ${FOLDER_FOR_MEDIA:?err}:/data
      - ${FOLDER_FOR_DATA:?err}/qbittorrent:/config
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - WEBUI_PORT=${WEBUI_PORT_QBITTORRENT:?err}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=${TP_THEME:?err}
      - QBITTORRENT_VERSION=5.0.1
## Do Not Change Network for qBittorrent
## qBittorrent MUST always use a VPN / Secure Internet connection
    network_mode: "service:gluetun"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - traefik.enable=true
    # ROUTERS
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${CLOUDFLARE_DNS_ZONE:?err}`)
      - traefik.http.routers.qbittorrent.entrypoints=secureweb
      - traefik.http.routers.qbittorrent.middlewares=authentik-forwardauth@file,security-headers@file,traefik-bouncer@file
    # SERVICES
      - traefik.http.services.qbittorrent.loadbalancer.server.scheme=http
      - traefik.http.services.qbittorrent.loadbalancer.server.port=${WEBUI_PORT_QBITTORRENT:?err}
    # MIDDLEWARES
```
